import { Meta } from '@storybook/react/types-6-0';
import { Story } from '@storybook/react';
import './button.css';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Get: Story<any>;
export declare const GetFromURL: Story<any>;
export declare const GetFromURLWithoutHeader: Story<any>;
export declare const Post: Story<any>;
export declare const PostFromURL: Story<any>;
export declare const PostFromURLWithoutHeader: Story<any>;
export declare const Put: Story<any>;
export declare const PutFromURL: Story<any>;
export declare const PutFromURLWithoutHeader: Story<any>;
export declare const Delete: Story<any>;
export declare const DeleteFromURL: Story<any>;
export declare const DeleteFromURLWithoutHeader: Story<any>;
export declare const Multipart: Story<any>;
export declare const MultipartFromURL: Story<any>;
